### ISSUE TITLE
images for kiss command

### ISSUE THREAD

**Issue by talmarko** [rem-bot-industries/rem-v2#125]

**Comment by talmarko** [comment]
https://cdn.discordapp.com/attachments/277519777449377794/282239845580013568/8R1n0hJ.jpg
https://cdn.discordapp.com/attachments/277519777449377794/282240025310134272/anime-black-boy-girl-Favim.com-3733727.jpg
https://cdn.discordapp.com/attachments/277519777449377794/282240073297035274/Black-And-White-Anime-Boy-Hard-Kiss-To-Girl-Wallpaper.jpg
https://cdn.discordapp.com/attachments/277519777449377794/282240399735521281/40071-Anime-Kiss-Arte-De-La-Espada-En-Linea-Kirito-Asuna.gif
https://cdn.discordapp.com/attachments/277519777449377794/282240428265439232/a5b892b2e5ea243029bdf25f48f6e16d.gif
https://cdn.discordapp.com/attachments/277519777449377794/282240446216929282/anime-cat-chibi-cute-Favim.com-4722517.gif
https://cdn.discordapp.com/attachments/277519777449377794/282240582057721866/lZ7gAES.gif
https://cdn.discordapp.com/attachments/277519777449377794/282240644930338816/tumblr_static_filename_640_v2.gif

**Comment by talmarko** [comment]
http://i.myniceprofile.com/1512/151229.gif
http://pa1.narvii.com/5822/71ef73672cd5dd6d53a2dde339bca15a2f9fc8da_hq.gif
https://media.giphy.com/media/12VXIxKaIEarL2/giphy.gif
http://68.media.tumblr.com/2b00d35e9237f5a456a864a7b7fdcadf/tumblr_mz5oxfRrVu1rx1dfqo1_r1_500.gif
https://s-media-cache-ak0.pinimg.com/originals/e3/4e/31/e34e31123f8f35d5c771a2d6a70bef52.gif
http://pa1.narvii.com/5848/0a46649e9e80c5c50459debb60ea827f32299416_hq.gif

**Comment by talmarko** [comment]
https://cdn.discordapp.com/attachments/274989585237540865/282241653165785088/tumblr_nb1ie95ezY1taeqnfo1_500.gif
https://cdn.discordapp.com/attachments/274989585237540865/282241627714617344/tumblr_mdu5yoBhnZ1rhgchxo1_500.gif
https://33.media.tumblr.com/e8228a8e3b323baf8fc9e79991780098/tumblr_n3w5vzg3KJ1qi1g2ao10_500.gif
http://24.media.tumblr.com/tumblr_mdegsoUwmX1rxf1iro1_500.gif
http://24.media.tumblr.com/5d51b3bbd64ccf1627dc87157a38e59f/tumblr_n5rfnvvj7H1t62gxao1_500.gif
http://25.media.tumblr.com/0a969f0c8ac5972ad663fc1a14f4663b/tumblr_mgbyvzpksK1rmdepbo1_500.gif
http://38.media.tumblr.com/84756421d21634f5f65d0d0f4c9da86f/tumblr_n2jz1jqEtq1sggrnxo1_500.gif
http://media.giphy.com/media/vHISzfc8dcVG0/giphy.gif#524157
http://37.media.tumblr.com/53bf74a951fc87a0cc15686f5aadb769/tumblr_n14rfuvCe41sc1kfto1_500.gif
http://31.media.tumblr.com/f9e5fab28c5fd389fad6789c3b18aa6f/tumblr_mxhlrnCvPi1rveihgo1_400.gif
http://i.myniceprofile.com/1486/148638.gif
https://media.giphy.com/media/HSgkuMRab3fK8/giphy.gif
http://24.media.tumblr.com/dc0496ce48c1c33182f24b1535521af2/tumblr_mqrl3ynedk1scihu7o1_500.gif
http://media.giphy.com/media/oHZPerDaubltu/giphy.gif
http://25.media.tumblr.com/tumblr_mcf25oETLX1r0ydwlo1_500.gif
http://www.lovethisgif.com/uploaded_images/41239-Anime-Cheek-Kiss-Gif-Karen-Kissing-Shino-lewd-.gif
http://i.mobofree.com/?u=http%3A%2F%2Fdata.whicdn.com%2Fimages%2F145488475%2Flarge.gif&w=600&h=1500
http://25.media.tumblr.com/3b8a73c70947679a6af56178762bdc1f/tumblr_mk8xzkenY71qzd219o1_500.gifhttps://68.media.tumblr.com/4cfb137bb0c61101caff4ef661ef99b6/tumblr_nlyakoSeA31u7pak7o1_500.gif
http://33.media.tumblr.com/tumblr_m7x4176tyH1ro4cfco1_500.gif
https://media.giphy.com/media/Z2sivLSfN8FH2/giphy.gif
http://anime-fanservice.org/coppermine/albums/K_galleries/Kiss_X_Sis_OAD/Kiss_X_Sis_OAD3-057.gif
http://i.imgur.com/Wkf4BjA.gif
https://media.giphy.com/media/ZRSGWtBJG4Tza/giphy.gif
http://24.media.tumblr.com/d4f03ca449e3d51325e9ba0cc6a11b24/tumblr_mmjr3zHgmw1s6qc3bo1_500.gif
http://media.giphy.com/media/X3ndlrK6rOCt2/giphy.gif
https://33.media.tumblr.com/b79a72b3f50f32e0a9819250814711e0/tumblr_nrwyl4hss81uwoitwo1_500.gif
http://24.media.tumblr.com/10bcb6c9307fc559e9d7fc45046c76d0/tumblr_ml7he1gYeU1snjuilo1_500.gif
http://media.giphy.com/media/514rRMooEn8ti/giphy.gif
http://media.tumblr.com/tumblr_mbawr10q0c1qfkm7e.gif
https://elrefugiodelosincomprendidos.files.wordpress.com/2013/03/nodame-cantabile-kiss.gif
http://media.giphy.com/media/zdY1ICmmWhW5a/giphy.gif
https://31.media.tumblr.com/52e2cd6735ac92efb15be079fc06fe3b/tumblr_msr6hvvRY61sh31wjo1_500.gif
http://i.imgur.com/hdZEXN3.gif
http://orig00.deviantart.net/5abd/f/2012/054/8/9/gray_x_lucy_kiss_animation_by_milady666-d4qqqf2.gif
https://media.giphy.com/media/EVODaJHSXZGta/giphy.gif
http://anime-gx.com/_txgx0/1393257265138.gif
http://s8.favim.com/orig/151119/akagami-no-shirayukihime-anime-boy-couple-Favim.com-3598058.gif
https://66.media.tumblr.com/9ef04153773078d26e47e497821b4638/tumblr_nypr79WJRb1uuqo27o1_500.gif

**Comment by talmarko** [comment]
https://puu.sh/u7Ja8/9e59ab0bc7.gif

**Comment by talmarko** [comment]
https://i.gyazo.com/7d310f4eb9f3fb25b2fda2bd1657ef5b.gif

**Comment by DasWolke** [comment]
added.
