### ISSUE TITLE
Add a pout cmd

### ISSUE THREAD

**Issue by DasWolke** [rem-bot-industries/rem-v2#130]

**Comment by talmarko** [comment]
https://68.media.tumblr.com/b34f76191aca81d172d984b8efd1fb1a/tumblr_o4ug71pfSH1tydz8to1_500.gif
https://68.media.tumblr.com/02dabf2a7299753f442feee1512e326c/tumblr_o2qhk8IoJs1tydz8to1_500.gif
https://68.media.tumblr.com/bdffb12c989187696de4605c92cc6488/tumblr_o7ey53enfU1v90u75o1_500.gif
http://imgwiz.com/images/2012/12/10/cMJn.gif
http://i.imgur.com/clpBDOi.gif
http://33.media.tumblr.com/f9fb055b0d291b8414e951670cd8cc67/tumblr_n3khg3pT321roo4dro3_500.gif
https://lh3.googleusercontent.com/-WzhtDCqiE10/V4BJyVNCo4I/AAAAAAAIplY/jJaL7iAIUb0d51oHZlAgDRO72PmqrDfGw/w506-h285/Omake%2BGif%2BAnime%2B-%2BNew%2BGame%2521%2B-%2BEpisode%2B1%2B-%2BYagami%2BPout.gif
https://68.media.tumblr.com/e145706e668a00aab79f13dac6f564d2/tumblr_nxc0nx0PZL1tydz8to1_500.gif
http://s.quickmeme.com/img/ba/bad51ab05a86676bf8a51cfda77ed4ab04aa5366feaaa5c558823781e88b7c8b.jpg
https://66.media.tumblr.com/edd9122a719a0d11f9ab9fa22a2496a6/tumblr_ng8r27XJw61t5kkdzo1_500.gif
http://66.media.tumblr.com/ec5797b4d5326113f08241a31a9df6b2/tumblr_o9paz89Rxb1twrse4o1_500.gif
https://cdn.awwni.me/t2jr.jpg
http://i.imgur.com/V0nzHKI.gif
http://68.media.tumblr.com/8093a7b7ca6e25ffbb393d3cfe02483d/tumblr_n0slkhd85j1rko1qvo2_500.gif
http://i.imgur.com/WUgRFsm.gif
https://img.ifcdn.com/images/4e459231029e1c5bea7c0fc3b1dd55b2ba2c9b3337a119cdd0285397a808ec7c_1.gif
https://s-media-cache-ak0.pinimg.com/originals/a0/c2/64/a0c264ad6b12b28d7c58871d7f5a999c.gif
http://i.imgur.com/SEpHNo0.gif
http://pa1.narvii.com/5805/6f8b4788caf1fc9f343ced4a93d43787a4022477_hq.gif
http://i.imgur.com/SlX7Zy3.gif
https://68.media.tumblr.com/ba73334eb74c46cb00a41ab2b4e2189c/tumblr_nhh3udqdtW1u3qei8o1_500.gif
http://i.imgur.com/A3vDoIJ.gif
https://33.media.tumblr.com/58bd9c7956ee9c961fc4095c25b8b751/tumblr_mipfpic6861qa94xto1_500.gif

**Comment by talmarko** [comment]
seems like i missed two xD
https://33.media.tumblr.com/05185a1c35222ae6c24d35da7c7dd9e0/tumblr_nt5tg2WBcS1r60zuio3_500.gif
http://scontent.cdninstagram.com/t51.2885-15/s480x480/e35/13562047_490111887849081_557262032_n.jpg?ig_cache_key=MTI4NTIxOTA2NjEyNzAyOTczNw%3D%3D.2

**Comment by Makujo** [comment]
angel beats only found 2 :(
https://media.giphy.com/media/14gYQTzByL7c6A/giphy.gif
https://media.giphy.com/media/OruxMjWAcUuxa/giphy.gif

**Comment by DasWolke** [comment]
@Makujo both of the images you sended are not really pouting, therefore not adding.
