### ISSUE TITLE
Rem returns TypeError when starting

### ISSUE THREAD

**Issue by yom21c1020** [rem-bot-industries/rem-v2#133]
I trying to run Rem on my own server. But I starting Rem, it returns `TypeError: Cannot read property 'on' of null at MOD.init.then (./src/shard.js:171:17)`. Can I fix it?

**Comment by DasWolke** [comment]
Mind sending me a screenshot of the full stacktrace ?

**Comment by yom21c1020** [comment]
Full stacktrace here.
![image](https://cloud.githubusercontent.com/assets/10514697/23342337/d1a91684-fc9b-11e6-9b6c-c09686e031df.png)

**Comment by DasWolke** [comment]
Alright, in /Rem/src/index.js, at line 106 edit this: `client = new Shard(0, 1, null, Raven);` to this: `client = new Shard(0, 1, undefined, Raven);`

**Comment by yom21c1020** [comment]
Thanks! I'll try that.
