### ISSUE TITLE
Rem doesn't find translation files

### ISSUE THREAD

**Issue by yom21c1020** [rem-bot-industries/rem-v2#134]
There are translation files properly but couldn't load files. Is there way to fix this?
![image](https://cloud.githubusercontent.com/assets/10514697/23343102/6e6c5302-fca9-11e6-9653-6619572a89fd.png)
![image](https://cloud.githubusercontent.com/assets/10514697/23343134/0a6c29e4-fcaa-11e6-8e1f-21c4749fc9e1.png)

**Comment by DasWolke** [comment]
rename locales to rem_translate

**Comment by yom21c1020** [comment]
but its name is rem_translate
![image](https://cloud.githubusercontent.com/assets/10514697/23343196/f5fd5f2c-fcaa-11e6-80ae-80af52c3fae3.png)

**Comment by DasWolke** [comment]
huh....

**Comment by DasWolke** [comment]
ah, i know, try the following: go into dist/ and then `node index.js`, I think it is caused by a different path, depending from where you start rem

**Comment by yom21c1020** [comment]
ah thanks!
