### ISSUE TITLE
!w.slap command images

### ISSUE THREAD

**Issue by talmarko** [rem-bot-industries/rem-v2#142]

**Comment by talmarko** [comment]
http://s1031.photobucket.com/user/shinnidan/media/Toradora_-_Taiga_Slap.gif.html
http://www.anime-fanservice.org/coppermine/albums/userpics/10205/Kirie_Slap_Attack.gif
http://s1224.photobucket.com/user/TehKL/media/_anime_doubleslap.gif.html
http://media.giphy.com/media/jLeyZWgtwgr2U/giphy.gif
http://media.giphy.com/media/iREUC7qrjN4vC/giphy.gif
http://media.giphy.com/media/RXGNsyRb1hDJm/giphy.gif
http://media.giphy.com/media/tMIWyF5GUrWwM/giphy.gif
http://pa1.narvii.com/5728/7b796b9cd6a6f44ef6b0aabee0d28d1351fdc7be_hq.gif
https://media.giphy.com/media/xXRDuvEcMA2JO/giphy.gif
http://i.imgur.com/lYxSTLA.gif
http://3.bp.blogspot.com/-CHYXl4bcgA0/UYGNzdDooBI/AAAAAAAADSY/MgmWVYn5ZR0/s400/2828+-+animated_gif+slap+umineko_no_naku_koro_ni+ushiromiya_maria+ushiromiya_rosa.gif
http://i.imgur.com/UXqzzab.gif
https://eruditeknight.files.wordpress.com/2014/06/1278328036202.gif
https://media.giphy.com/media/10Am8idu3qBYRy/giphy.gif
http://img.mrdrsr.net/slap.gif
http://www.funnyjunk.com/Epic+bitch+slap/funny-gifs/4981808#325276_4981364
http://i.imgur.com/1kJpP.gif
http://subarashii.me/wp-content/uploads/2013/07/360mlgpro-bitch-slap.gif
http://safebooru.org/images/360/0bbb2921c4237b342c1e0b9028c1bb5d5cafb667.gif
http://i.imgur.com/0G5uqlN.gif
https://media.giphy.com/media/Zau0yrl17uzdK/giphy.gif
http://safebooru.org/images/363/5b1a06da49bd1eeccbf1f60428370c9b491b5156.gif?363332
http://orig09.deviantart.net/14ed/f/2010/197/9/4/misty_slap_ash_by_iresistableashgirl.gif
https://media.giphy.com/media/frNZmtLwVVhrG/giphy.gif
http://media.giphy.com/media/RdnJnbQ0lYGCQ/giphy.gif
http://media.tumblr.com/tumblr_lt8iz1olL51qdsjb2.gif
https://38.media.tumblr.com/2c7281f46876dd1776aa5e642d046067/tumblr_n3dmf0in3K1snpm91o5_500.gif
https://media.giphy.com/media/3mqco6JAjzobu/giphy.gif
https://31.media.tumblr.com/tumblr_mc2h7o0TBQ1rz3uiso1_500.gif
http://24.media.tumblr.com/tumblr_m4jl21EyuP1qjricxo1_500.gif
http://25.media.tumblr.com/tumblr_m1nsxc3jUu1qdjfd8o1_400.gif
http://media.tumblr.com/tumblr_lx84j9KIBZ1qg12e8.gif
https://reallifeanime.files.wordpress.com/2014/06/akari-slap.gif
http://smg.photobucket.com/user/Jorawr/media/anime%20gifs/slap.gif.html
https://media.tenor.co/images/5ab22ca640af20cd3b479694bde9e25c/raw
https://33.media.tumblr.com/07bada8d22bec984877b1f9b94b1c1f1/tumblr_mmcor2nb8b1qj5jqso1_500.gif
http://33.media.tumblr.com/tumblr_ls57ox8e0K1qagrb6o1_500.gif
http://img.realurl.org/images/570x363/crunchyroll-forum-gif-animations-page-114-11664.gif
http://img.realurl.org/images/570x363/published-at-425-241-in-umineko-no-naku-koro-ni-episode-ii-ii-pimp-11666.gif
http://s407.photobucket.com/user/Daxdiv/media/GIF%20Party/slapfight.gif.html
https://artemisunfiltered.files.wordpress.com/2014/05/golden-time-nana-slap.gif

**Comment by DasWolke** [comment]
added.
