### ISSUE TITLE
gifs for lick command

### ISSUE THREAD

**Issue by talmarko** [rem-bot-industries/rem-v2#148]

**Comment by talmarko** [comment]
https://media.giphy.com/media/x4P8TaYhGn4FW/giphy.gif
http://i.imgur.com/g5xAa4i.gif
https://m.popkey.co/0565e9/bgq1Y.gif
http://orig10.deviantart.net/20c8/f/2013/215/8/d/lick_2_by_anime_wolfz-d6gi186.gif
http://data.whicdn.com/images/47385822/large.gif
https://media.giphy.com/media/JUrjTvzTbTUME/giphy.gif
http://i1.kym-cdn.com/photos/images/newsfeed/000/979/257/de4.gif
https://s-media-cache-ak0.pinimg.com/originals/4b/f3/5e/4bf35e6c5b95ae0f4a5d83b84f56f10c.gif
https://media.giphy.com/media/NzbcdfP2B6GKk/giphy.gif
http://pa1.narvii.com/5852/4b2e3040af4d801e1ac34a3b196e2c85cb914dfc_hq.gif
http://media0.giphy.com/media/dKjkpySoZnfhe/giphy.gif

**Comment by DasWolke** [comment]
added to rra and rem alpha
