### ISSUE TITLE
Cleverbot isn't working

### ISSUE THREAD

**Issue by EraySP909** [rem-bot-industries/rem-v2#160]
X An error with cleverbot occured!

**Comment by DasWolke** [comment]
The cleverbot api from cleverbot.io is not working anymore, as it has gotten pay only too.
Currently we can not do much against it.

**Comment by Underforest** [comment]
Now it's working! Maybe close this issue already?

**Comment by DasWolke** [comment]
yup. ^^

**Comment by Underforest** [comment]
again not working lmao
