### ISSUE TITLE
Config problem

### ISSUE THREAD

**Issue by alapaches** [rem-bot-industries/rem-v2#219]
Hello !

I'm sorry I'm rather new with node and mongodb but it seems I got a issue here : 

When I'm done with everything, trying to launch indes.js doesn't seem to work. I did the whole tutorial in the readme.md but it seems that it can't connect to the redis ip. Could you help me to find a way to fix this or tell me where I made a mistake ?
Here is the thing I mentionned before : 
![image](https://user-images.githubusercontent.com/13233376/46761449-c8468d00-ccd4-11e8-97d6-ae7516b6f5ef.png)
Thank you !

**Comment by sevrino** [comment]
Did you run the redis server?

**Comment by DasWolke** [comment]
Sevrino's comment tells you the solution, so I'm closing this issue.
